<?php
/**
 * Created by PhpStorm.
 * User: Yacine
 * Date: 11/13/2018 0013
 * Time: 12:05 AM
 */
ob_start();
?>
<form action="../../../index.php" method="post">
    <fieldset>
        <legend> Inscription</legend>
        <div class="clear"></div>
        <table class="container">
            <tr>
                <td><label for="Pseudo">Pseudo: </label></td>
                <td><input type="text" name="Pseudo" id="Pseudo"></td>
            </tr>
            <tr>
                <td><label for="Pass">Mot de passe : </label></td>
                <td><input type="text" name="Pass" id="Pass"></td>
            </tr>
            <tr>
                <td><p></p></td>
                <td>
                    <p>
                        <button type="submit" id="Ajouter" name="Inscription">Ajouter</button>
                        <button type="reset" id="Annuler">Annuler</button>
                    </p>
                </td>
            </tr>
        </table>
    </fieldset>
</form>
<?php
$content = ob_get_clean();
$title = 'page d\'inscription';
require 'view/frontEnd/layout.phtml';
?>