<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title><?= $title ?></title>
    <link rel="stylesheet" href="public/css/normalize-3.0.3.min.css">
    <link rel="stylesheet" href="public/vendors/fontawesome5.5/css/all.css">
    <link rel="stylesheet" href="public/css/main.css">
    <script src="public/js/main.js"></script>
</head>
<body>
<div id="red"></div>
<header>
    <h1><a href="index.php"><img src="public/images/logo.gif" alt="logo 3wa">Restaurant - Made in
            America</a></h1>
    <div id="login_group">
        <?php if (!isset($_SESSION['user'])) { ?>
            <a href="index.php?action=SignUp">créer un compte</a>
            <a id="Connexion" class="active">Connexion</a>
            <section id="section_connexion" style="display: none">
                <form action="index.php?action=LogIn" method="post">
                    <input type="text" placeholder="email" name="email" id="email">
                    <input type="password" placeholder="Mot de passe" name="mdp">
                    <button class="active" type="submit" name="Connexion">Connexion</button>
                </form>
            </section>
        <?php } else { ?>
            <a href="index.php?action=Account" style="">Mon compte</a>
            <a href="index.php?action=reservation" style="">Reserver une table</a>
            <a href="index.php?action=order" style="">commander des aliments</a>
            <a href="index.php?action=LogOff" style="">Deconnexion</a>
        <?php } ?>
    </div>
</header>
<?= $content ?>
<footer>
    <img src="public/images/payment/mastercard.png" alt="mastercard">
    <img src="public/images/payment/paypal.png" alt="paypal">
    <img src="public/images/payment/visa.png" alt="visa">
    <p>Réalisé avec <i class="fas fa-heart"></i> par les éléves de la 3W academy</p>
</footer>
</body>
</html>