<?php ob_start();
?>
    <style>
        .Content_Admin_home {
            display: flex;
            flex-direction: row;
            flex-wrap: nowrap;
            justify-content: space-between;
        }

        .Content_Admin_home a {
            flex-basis: 25%;
            text-align: center;
            height: 1rem;
            background: red;
            padding: 1%;
            margin: 1%;
            border-radius: 5px;
            text-decoration: none;
            color: white;
        }
    </style>
    <main class="Content_Admin_home">

        <a href="index.php?action=AddMeal" title="Rajout d'aliment a la liste disponible">
            Editer aliments
        </a>

        <a href="index.php?action=EditMeal" title="Rajout d'aliment a la liste disponible">
            Ajouter aliment
        </a>

        <a href="index.php?action=AdministrationReservation" title="Rajout d'aliment a la liste disponible">
            voir les reservation
        </a>
        <a href="index.php?action=EditCommande" title="Rajout d'aliment a la liste disponible">
            gerer les commandes
        </a>

    </main>

<?php $content = ob_get_clean();
$title = 'page d\'administration';
require 'view/layout.phtml'; ?>