    <?php ob_start();?>
    <main class="Content_Admin_home">

        <a href="index.php?action=Meals" title="Editer la liste d'aliment disponible">
            Gestion des aliments
        </a>

        <a href="index.php?action=AdministrationReservation" title="Rajout d'aliment a la liste disponible">
            Gestion des reservations
        </a>

        <a href="index.php?action=EditCommande" title="gestion des commande displonible">
            Gestion des commandes
        </a>

    </main>

<?php $content = ob_get_clean();
$title = 'page d\'administration';
require 'view/layout.phtml'; ?>