<?php ob_start(); ?>
<style>

</style>
<main class="center">
<form action="index.php?action=EditMeal" method="post">
    <fieldset>
        <table>
            <legend><i class="fas fa-check"></i> Caractéristiques </legend>
            <tr>
                <td>Nom : </td>
                <td><input type="text" name="nom" value="<?= $donnees['name'] ?>"></td>
            </tr>
            <tr>
                <td>Description : </td>
                <td><textarea name="description" id="" cols="30" rows="10"><?= $donnees['description'] ?></textarea></td>
            </tr>
            <tr>
                <td>Categorie : </td>
                <td><input type="text" name="Categorie" value="<?= $donnees['categories'] ?>"></td>
            </tr>
            <tr>
                <td>nom du fichier : </td>
                <td><input type="text" name="filename" value="<?= $donnees['photo'] ?>"></td>
            </tr>   
        </table>
</fieldset>
    <fieldset class="field2">
        <table>
            <legend><i class="fas fa-retweet"></i> Approvisionnement</legend>
            <tr>
                <td>Stock initial :</td>
                <td><input type="number" name="stock" value="<?= $donnees['stock'] ?>"></td>
            </tr>
            <tr>
                <td>prix d'achat :</td>
                <td><input type="number" name="achat" value="<?= $donnees['prix_achat'] ?>"> €</td>
            </tr>
            <tr>
                <td>Prix de vente :</td>
                <td><input type="number" name="vente" value="<?= $donnees['prix_vente'] ?>"> €</td>
            </tr>        
        </table>
    </fieldset>
    <input type="hidden" name="id" value="<?=  $donnees['id'] ?>">
    <button type="submit" name="Submitedit" id="valider" class="créer">Editer</button>
    <button type="button" id="vider" class="annuler">Annuler</button>
</form>
</main>
<?php $content = ob_get_clean();
$title = 'Gestion aliments';
require 'view/layout.phtml'; ?>