<?php ob_start(); ?>
<main>
	<h2>Liste des aliments :</h2>
	<a href="index.php?action=AddMeal"><i class="fas fa-plus"></i>Ajouter un aliment</a>
	<table style="width:100%">
		<tr>
			<th>id</th>
			<th>nom</th>
			<th>categories</th>
			<th>description</th>
			<th>prix achat</th>
			<th>prix vente</th>
			<th>stock</th>
			<th>photo</th>
			<th>Editer</th>
			<th>supprimer</th>
		</tr>
		<?php foreach($liste_aliment as $aliment) {  ?>
		<tr>
			<td><p><?= $aliment['id'] ?></p></td>
			<td><p><?= $aliment['name'] ?></p></td>
			<td><p><?= $aliment['categories'] ?></p></td>
			<td><p><?= substr($aliment['description'], 0, 60).'...' ?></p></td>
			<td><p><?= $aliment['prix_achat']  ?> €</p>  </td>
			<td><p><?= $aliment['prix_vente']  ?> €</p>  </td>
			<td><p><?= $aliment['stock'] ?></p> </td>
			<td><p><?= $aliment['photo'] ?></p> </td>
			<td>
			<form action="index.php?action=EditMeal" method="post">
			<input type="hidden" name="id" value="<?= $aliment['id'] ?>">
				<button type="submit" name="edit"><i class="fas fa-pen"></i></button>
			</form>
			</td>
			<td>
			<form action="index.php?action=Meals" method="post">
			<input type="hidden" name="id" value="<?= $aliment['id'] ?>">
				<button type="submit" name="delete"><i class="fas fa-times"></i></button>
			</form>
			</td>
		</tr>

	<?php } ?>

	</table>
</main>
<?php $content = ob_get_clean();
$title = 'Gestion aliments';
require 'view/layout.phtml'; ?>